### ISSUE TITLE
KeyNotFoundException when instanceToListenerDistances already cleared & emitter > Max Distance

### ISSUE THREAD

**Issue by ianberman** [VilleOjala/FMOD-Unity-Tools#4]
```
KeyNotFoundException: The given key was not present in the dictionary.
System.Collections.Generic.Dictionary`2[TKey,TValue].get_Item (TKey key) (at <695d1cc93cca45069c528c15c9fdd749>:0)
FMODUnityTools.SpatialAudioManager.CalculatePropagationCosts (System.Collections.Generic.List`1[T] instances) (at Assets/Plugins/AudioTools/Scripts/Runtime/Extensions/SpatialAudioSystem/SpatialAudioManager.cs:830)
FMODUnityTools.SpatialAudioManager.LateUpdate () (at Assets/Plugins/AudioTools/Scripts/Runtime/Extensions/SpatialAudioSystem/SpatialAudioManager.cs:374)
```

I believe this is happening because `instanceToListenerDistances` is being cleared before CheckInstanceAudibility() and later CalculatePropagationCosts() are called.

Steps to reproduce:
Place an emitter within one room, then move the player/listener to another room, and walk out of range (beyond the FMOD event's max distance).

Steps I tried to solve:
Only calling CalculatePropagationCosts() if `instanceToListenerDistances > 0`
However it breaks again if you have more than one emitter and you're out of range of one, while being within range of the other.

Let me know if I am overlooking something, or I will take another look later this week :)

**Comment by VilleOjala** [comment]
![Issue #4](https://user-images.githubusercontent.com/69209034/226538201-bea4a28c-bbae-4984-8611-edb73512837b.png)

Good catch. I pushed the above simple fix for the problem. Let me know if you experience any side effects from it.

**Comment by ianberman** [comment]
After some initial testing, it seems to have fixed the issue - the only thing to note is, all the sounds currently playing (but inaudible) still appear in the debug section of the inspector of Spatial Audio Manager, which I assume is intended. They are not updating calculations, just appear holding the last calculated value. Below screenshot is of two sounds when player is out of max distance of the fmod event, with the values not updating.
<img width="503" alt="Screen Shot 2023-03-21 at 8 00 32 PM" src="https://user-images.githubusercontent.com/32076251/226713789-4972d825-3ca1-4635-844c-c255086d6425.png">

**Comment by VilleOjala** [comment]
Yep, leaving the out-of-range sounds as they were is intended.
